#!/bin/bash
set -eu

export BIN=bin

ver=$(uncrustify --version)
if [ ! "$ver" = "uncrustify 0.64" ] ; then
  echo "Bad version of uncrustify, skipping formatting"
else
  find src -name "*.cpp" -or -name "*.h" | while read f; do
  uncrustify -q -c scripts/uncrustify.cfg --no-backup "$f"
done
fi

make -j`nproc`

readonly t1=$(date +%s)
./tests/run.sh
readonly t2=$(date +%s)
echo "$((t2-t1))s"

