#!/bin/bash
set -eu

export BIN=bin

ver=$(uncrustify --version)
if [ ! "$ver" = "uncrustify 0.64" ] ; then
  echo "Bad version of uncrustify, skipping formatting"
else
  find src -name "*.cpp" -or -name "*.h" | while read f; do
  uncrustify -q -c scripts/uncrustify.cfg --no-backup "$f"
done
fi

if [ $(uname -s) == "Darwin" ]; then
  CORES=$(sysctl -n hw.logicalcpu)
else
  CORES=$(nproc)
fi

make -j$CORES

readonly t1=$(date +%s)
./tests/run.sh
readonly t2=$(date +%s)
echo "$((t2-t1))s"

